package cmsys.View;

public class FinalSubmitPanel extends javax.swing.JPanel {

    /**
     * Creates new form finalSubmitPanel
     */
    public FinalSubmitPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptionLabel = new javax.swing.JLabel();
        instructionDesLabel = new javax.swing.JLabel();
        getTemplateFileButton = new javax.swing.JButton();
        selectFinalVersionButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jSeparatorButtom = new javax.swing.JSeparator();
        closeButton = new javax.swing.JButton();
        titleDesPanel = new javax.swing.JLabel();

        descriptionLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        descriptionLabel.setText("<html>Congratulations!<br>Your paper has been accepted! Please submit the final version of your paper.</html>");

        instructionDesLabel.setText("<html><b>Instruction:</b><br>Re-format your paper as the template file provided.</html>");

        getTemplateFileButton.setText("Get the template file");

        selectFinalVersionButton.setText("Submit the final version");

        fileNameLabel.setText("No file selected");

        submitButton.setText("Submit");

        closeButton.setText("Close");

        titleDesPanel.setText("Title:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorButtom)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instructionDesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getTemplateFileButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectFinalVersionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileNameLabel))
                            .addComponent(titleDesPanel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titleDesPanel)
                .addGap(18, 18, 18)
                .addComponent(instructionDesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(getTemplateFileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFinalVersionButton)
                    .addComponent(fileNameLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(closeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JButton getTemplateFileButton;
    private javax.swing.JLabel instructionDesLabel;
    private javax.swing.JSeparator jSeparatorButtom;
    private javax.swing.JButton selectFinalVersionButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleDesPanel;
    // End of variables declaration//GEN-END:variables
}
