package cmsys.View;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import java.util.*;

import cmsys.PaperManagement.*;
import cmsys.Common.*;
import cmsys.UserManagement.*;

public class MyPapersPanel extends javax.swing.JPanel {

    public MyPapersPanel() {
    	UserDefault userDefault = UserDefault.getInstance();
    	
    	user = (User)userDefault.getObj("user");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    private void initComponents() {

        submittionDeadlinelabel = new javax.swing.JLabel();
        jSeparatorTop = new javax.swing.JSeparator();
        filterDesLabel = new javax.swing.JLabel();
        filterComboBox = new javax.swing.JComboBox();
        jSeparatorMid = new javax.swing.JSeparator();
        submitButton = new javax.swing.JButton();
        papersScrollPane = new javax.swing.JScrollPane();
        papersTable = new javax.swing.JTable();
        responseButton = new javax.swing.JButton();
        submitFinalVersionButton = new javax.swing.JButton();
        viewPaperDetailsButton = new javax.swing.JButton();

        submittionDeadlinelabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        submittionDeadlinelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        try {
			submittionDeadlinelabel.setText("Submittion deadline: " + Settings.getSettingFromDB("submissionDeadline"));
		} catch (CmsysException e) {
			
		}

        filterDesLabel.setText("Filter:");

        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Submitted", "Awaiting response", "Accepted - Awaiting final version submittion", "Accepted", "Rejected" }));

        submitButton.setText("+ Paper");

        try {
			updateTable();
		} catch (CmsysException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
        papersScrollPane.setViewportView(papersTable);

        responseButton.setText("Response to the reviews");

        submitFinalVersionButton.setText("Submit final version");

        viewPaperDetailsButton.setText("View paper details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(filterDesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(papersScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jSeparatorMid)
                            .addComponent(submittionDeadlinelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparatorTop))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(responseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitFinalVersionButton)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitButton)
                            .addComponent(viewPaperDetailsButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submittionDeadlinelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorTop, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterDesLabel)
                    .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorMid, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(papersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewPaperDetailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responseButton)
                    .addComponent(submitFinalVersionButton))
                .addGap(24, 24, 24))
        );
        
        submitFinalVersionButton.setEnabled(false);
        viewPaperDetailsButton.setEnabled(false);
        responseButton.setEnabled(false);
        
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	submitButtonActionPerformed();
            }
        });
        
        submitFinalVersionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	submitFinalVersionButtonActionPerformed();
            }
        });
        
        filterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	String text = (String)(filterComboBox.getSelectedItem());
            	
            	RowFilter<Object, Object> filter = new RowFilter<Object, Object>() {
            			public boolean include(Entry entry) {
            				String status = (String)entry.getValue(1);
            				if (((String)(filterComboBox.getSelectedItem())).equals("All"))
            					return true;
            				return ((String)(filterComboBox.getSelectedItem())).equals(status);
            			}
            	};
            	
            	TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
            	sorter.setRowFilter(filter);
            	papersTable.setRowSorter(sorter);
            }
        });
        
        
        papersTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent evt) {
				//if (papersTable.getModel().getValueAt(papersTable.getSelectedRow(), 1).equals(")
				viewPaperDetailsButton.setEnabled(true);
			}
        });
    }
    
    private void submitButtonActionPerformed() {
    	JDialog dialog = new JDialog();
    	
    	dialog.setTitle("New submittion");
    	dialog.setContentPane(new SubmitPanel());
    	dialog.pack();
    	dialog.setLocationRelativeTo(this);
    	dialog.setVisible(true);
    }
    
    private void submitFinalVersionButtonActionPerformed() {
    	JDialog dialog = new JDialog();
    	
    	dialog.setTitle("Final version submittion");
    	dialog.setContentPane(new FinalSubmitPanel());
    	dialog.pack();
    	dialog.setLocationRelativeTo(this);
    	dialog.setVisible(true);
    }
    
    @SuppressWarnings("serial")
	private void updateTable() throws CmsysException {
    	Settings settings = Settings.getInstance();
    	Object[][] paperObj = null;
    	ArrayList<Paper> paperList = Paper.getPaperListByUid(user.getUID());
    	
    	paperObj = new Object[paperList.size()][2];
    	
    	for (int i = 0; i < paperList.size(); i++) {
    		paperObj[i][0] = paperList.get(i).getTitle();
    		paperObj[i][1] = Status.toString(paperList.get(i).getStatus(), user.getRole());
    	}
    	
    	model = (new javax.swing.table.DefaultTableModel(paperObj, new String [] {"Title", "Status"})
    			{public boolean isCellEditable(int row, int column){return false;}});

    	papersTable.setModel(model);
    }
    
    private javax.swing.JComboBox filterComboBox;
    private javax.swing.JLabel filterDesLabel;
    private javax.swing.JSeparator jSeparatorMid;
    private javax.swing.JSeparator jSeparatorTop;
    private javax.swing.JScrollPane papersScrollPane;
    private javax.swing.JTable papersTable;
    private javax.swing.JButton responseButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel submittionDeadlinelabel;
    private javax.swing.JButton submitFinalVersionButton;
    private javax.swing.JButton viewPaperDetailsButton;
    private javax.swing.table.DefaultTableModel model;
    private User user;
}
