package cmsys.View;

public class SubmitPanel extends javax.swing.JPanel {

    /**
     * Creates new form submitPanel
     */
    public SubmitPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleDesLabel = new javax.swing.JLabel();
        abstractDesLabel = new javax.swing.JLabel();
        pdfWhButton = new javax.swing.JButton();
        pdfWohButton = new javax.swing.JButton();
        titleTextField = new javax.swing.JTextField();
        abstractScrollPane = new javax.swing.JScrollPane();
        abstractTextArea = new javax.swing.JTextArea();
        addAuthorPanel = new javax.swing.JPanel();
        authorsDesLabel = new javax.swing.JLabel();
        authorsScrollPane = new javax.swing.JScrollPane();
        authorsList = new javax.swing.JList();
        addAuthorButton = new javax.swing.JButton();
        removeAuthorButton = new javax.swing.JButton();
        addKeywordPanel = new javax.swing.JPanel();
        keywordsDesLabel = new javax.swing.JLabel();
        keywordsScrollPane = new javax.swing.JScrollPane();
        keywordsList = new javax.swing.JList();
        addKeywordButton = new javax.swing.JButton();
        removeKeywordButton = new javax.swing.JButton();
        pdfWhFileNameLabel = new javax.swing.JLabel();
        pdfWohFileNameLabel = new javax.swing.JLabel();
        jSeparatorBottom = new javax.swing.JSeparator();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        titleDesLabel.setText("Title*:");

        abstractDesLabel.setText("Abstract*:");

        pdfWhButton.setText("PDF file with header");
        pdfWhButton.setToolTipText("");

        pdfWohButton.setText("PDF file without header");

        abstractTextArea.setColumns(20);
        abstractTextArea.setRows(5);
        abstractScrollPane.setViewportView(abstractTextArea);

        authorsDesLabel.setText("Authors*:");

        authorsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        authorsScrollPane.setViewportView(authorsList);

        addAuthorButton.setText("+");

        removeAuthorButton.setText("-");
        removeAuthorButton.setToolTipText("");

        javax.swing.GroupLayout addAuthorPanelLayout = new javax.swing.GroupLayout(addAuthorPanel);
        addAuthorPanel.setLayout(addAuthorPanelLayout);
        addAuthorPanelLayout.setHorizontalGroup(
            addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorPanelLayout.createSequentialGroup()
                .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorsDesLabel)
                    .addGroup(addAuthorPanelLayout.createSequentialGroup()
                        .addComponent(authorsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addAuthorButton)
                            .addComponent(removeAuthorButton))))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        addAuthorPanelLayout.setVerticalGroup(
            addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAuthorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorsDesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addAuthorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addAuthorPanelLayout.createSequentialGroup()
                        .addComponent(addAuthorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeAuthorButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        keywordsDesLabel.setText("Keywords*:");

        keywordsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        keywordsScrollPane.setViewportView(keywordsList);

        addKeywordButton.setText("+");

        removeKeywordButton.setText("-");
        removeKeywordButton.setToolTipText("");

        javax.swing.GroupLayout addKeywordPanelLayout = new javax.swing.GroupLayout(addKeywordPanel);
        addKeywordPanel.setLayout(addKeywordPanelLayout);
        addKeywordPanelLayout.setHorizontalGroup(
            addKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addKeywordPanelLayout.createSequentialGroup()
                .addComponent(keywordsDesLabel)
                .addGap(0, 256, Short.MAX_VALUE))
            .addGroup(addKeywordPanelLayout.createSequentialGroup()
                .addComponent(keywordsScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addKeywordButton)
                    .addComponent(removeKeywordButton)))
        );
        addKeywordPanelLayout.setVerticalGroup(
            addKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addKeywordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keywordsDesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keywordsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addKeywordPanelLayout.createSequentialGroup()
                        .addComponent(addKeywordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeKeywordButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pdfWhFileNameLabel.setText("File not selected");

        pdfWohFileNameLabel.setText("File not selected");

        submitButton.setText("Submit");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pdfWohButton)
                            .addComponent(pdfWhButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pdfWhFileNameLabel)
                            .addComponent(pdfWohFileNameLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(abstractDesLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(abstractScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleDesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addAuthorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addKeywordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparatorBottom, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleDesLabel)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(abstractDesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(abstractScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addAuthorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addKeywordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdfWhButton)
                    .addComponent(pdfWhFileNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdfWohButton)
                    .addComponent(pdfWohFileNameLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abstractDesLabel;
    private javax.swing.JScrollPane abstractScrollPane;
    private javax.swing.JTextArea abstractTextArea;
    private javax.swing.JButton addAuthorButton;
    private javax.swing.JPanel addAuthorPanel;
    private javax.swing.JButton addKeywordButton;
    private javax.swing.JPanel addKeywordPanel;
    private javax.swing.JLabel authorsDesLabel;
    private javax.swing.JList authorsList;
    private javax.swing.JScrollPane authorsScrollPane;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSeparator jSeparatorBottom;
    private javax.swing.JLabel keywordsDesLabel;
    private javax.swing.JList keywordsList;
    private javax.swing.JScrollPane keywordsScrollPane;
    private javax.swing.JButton pdfWhButton;
    private javax.swing.JLabel pdfWhFileNameLabel;
    private javax.swing.JButton pdfWohButton;
    private javax.swing.JLabel pdfWohFileNameLabel;
    private javax.swing.JButton removeAuthorButton;
    private javax.swing.JButton removeKeywordButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleDesLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
